---
- name: create secret
  community.docker.docker_secret:
    name: secret
    data: "{{ lookup('file', '.env') | b64encode }}"
    labels:
      secret: "{{ lookup('file', '.env') | hash('sha1') }}"
    data_is_b64: true
    state: present
