---
- name: up nginx
  community.docker.docker_swarm_service:
    name: MyNginx
    image: "nginx:{{ nginx_vercion }}"
    #state: "present" #используется по умолчанию
    networks:
      - name: "{{ network_name }}"
    publish:
      - published_port: 8081
        target_port: 80
        protocol: tcp
        mode: ingress
    replicas: 5
    configs:
      - config_name: nginx.conf
        filename: /etc/nginx/conf.d/nginx.conf
        mode: 0444
      - config_name: index.html
        filename: /usr/share/nginx/html/index.html
        mode: 0444
