---
- name: install docker
  become: true
  block:
    - name: Add universe
      apt_repository:
        repo: "deb http://us.archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} universe"
        state: present
    - name: Installing additional packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - python3-pip
        update-cache: true
        cache_valid_time: 86400
    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present
        update_cache: true
    - name: Installing docker-ce
      apt:
        name: docker-ce
        update-cache: true
    - name: Checking that docker-ce is installed and rebooted
      service:
        name: docker
        state: restarted
        enabled: yes
    - name: Add a user to a docker group
      user:
        name: "{{ ansible_user }}"
        group: docker
        append: true
    - name: Add a docker module
      pip:
        name: docker
    - name: reboot
      reboot:
